export enum ActionConstent {
    RESET_STATE = 'RESET_STATE',
    SET_TASKS = 'SET_TASKS',
    SET_TASK = 'SET_TASK',
    REMOVE_TASK = 'REMOVE_TASK',
    UPDATE_TASK = 'UPDATE_TASK',
    SET_STATUSES = 'SET_STATUSES',
    SET_GROUPS = 'SET_GROUPS',
    SET_GROUP = 'SET_GROUP',
    REMOVE_GROUP = 'SET_GROUP',
    UPDATE_GROUP = 'UPDATE_GROUP',
    SET_LOADER = 'SET_LOADER',
    UPDATE_TASK_ON_DRAG = 'UPDATE_TASK_ON_DRAG'
}